# ____________________ 1. PersistentVolumeClaim for Inventory DB ____________________

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventory-db-pvc
  namespace: ecommerce
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---

# ____________________ 2. Deployment for Inventory DB ____________________

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-db
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-db
  template:
    metadata:
      labels:
        app: inventory-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: inventory_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: inventory-db-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", $(POSTGRES_USER), "-d", "inventory_db"]
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: inventory-db-storage
          persistentVolumeClaim:
            claimName: inventory-db-pvc

---

# ____________________ 3. Service for Inventory DB ____________________

apiVersion: v1
kind: Service
metadata:
  name: inventory-db
  namespace: ecommerce
spec:
  selector:
    app: inventory-db
  ports:
    - port: 5432
      targetPort: 5432
