# Generated by Django 4.2.7 on 2026-04-16 18:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carrier', models.CharField(choices=[('aramex', 'Aramex'), ('bosta', 'Bosta'), ('mkh', 'Mostafa Khalifa Shipping')], max_length=20)),
                ('service_type', models.CharField(max_length=100)),
                ('tracking_number', models.CharField(max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('label_created', 'Label Created'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('destination_address', models.TextField(blank=True, help_text='Snapshot of the destination address at the time of shipment creation', null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight_unit', models.CharField(choices=[('oz', 'Ounces'), ('g', 'Grams'), ('kg', 'Kilograms')], default='g', max_length=10)),
                ('length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('package_type', models.CharField(default='package', max_length=50)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('estimated_delivery', models.DateField(null=True)),
                ('actual_delivery', models.DateTimeField(null=True)),
                ('label_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_zip', models.CharField(max_length=10)),
                ('destination_zip', models.CharField(max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dimensions_hash', models.CharField(max_length=64)),
                ('carrier', models.CharField(choices=[('aramex', 'Aramex'), ('bosta', 'Bosta'), ('mkh', 'Mostafa Khalifa Shipping')], max_length=20)),
                ('service_type', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transit_days', models.IntegerField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['origin_zip', 'destination_zip', 'weight'], name='shipping_sh_origin__72a38a_idx'), models.Index(fields=['expires_at'], name='shipping_sh_expires_4af5d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('event_description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('event_time', models.DateTimeField()),
                ('carrier_event_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='shipping.shipment')),
            ],
            options={
                'ordering': ['-event_time'],
                'indexes': [models.Index(fields=['shipment', 'event_time'], name='shipping_tr_shipmen_1fb0a8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['order'], name='shipping_sh_order_i_cb7c84_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_number'], name='shipping_sh_trackin_af3d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['carrier', 'status'], name='shipping_sh_carrier_86be7d_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['created_at'], name='shipping_sh_created_93a1f0_idx'),
        ),
    ]
