# Generated by Django 4.2.7 on 2026-04-16 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('recommended_products', models.JSONField()),
                ('recommendation_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_recommendation_cache',
                'unique_together': {('user_id', 'recommendation_type')},
            },
        ),
        migrations.CreateModel(
            name='UserProductInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('add_to_cart', 'Add to Cart'), ('purchase', 'Purchase'), ('wishlist', 'Add to Wishlist'), ('search', 'Search')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.FloatField(default=1.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='products.product')),
            ],
            options={
                'db_table': 'user_product_interactions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', '-timestamp'], name='user_produc_user_id_0ce3b8_idx'), models.Index(fields=['product', '-timestamp'], name='user_produc_product_b2ef3a_idx'), models.Index(fields=['session_id', '-timestamp'], name='user_produc_session_af3b51_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('similarity_type', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_products', to='products.product')),
                ('similar_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='products.product')),
            ],
            options={
                'db_table': 'product_similarities',
                'ordering': ['-similarity_score'],
                'indexes': [models.Index(fields=['product', '-similarity_score'], name='product_sim_product_8b2ed6_idx')],
                'unique_together': {('product', 'similar_product', 'similarity_type')},
            },
        ),
        migrations.CreateModel(
            name='FrequentlyBoughtTogether',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(default=1)),
                ('confidence', models.FloatField(default=0.0)),
                ('product1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_with', to='products.product')),
                ('product2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_with_reverse', to='products.product')),
            ],
            options={
                'db_table': 'frequently_bought_together',
                'ordering': ['-confidence', '-frequency'],
                'unique_together': {('product1', 'product2')},
            },
        ),
    ]
