# _____________________________ Deployment for Cart Service _____________________________

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      initContainers:
      - name: migrate
        image: khalifa035/cart-service:latest
        command: ["python", "manage.py", "migrate", "--noinput"]
        env:
        - name: DB_HOST
          value: cart-db
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: cart_db
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cart-service-secret
              key: DB_PASSWORD
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: cart-service-secret
              key: SECRET_KEY
      containers:
      - name: cart-service
        image: khalifa035/cart-service:latest
        env:
        - name: DB_HOST
          value: cart-db
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: cart_db
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cart-service-secret
              key: DB_PASSWORD
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: cart-service-secret
              key: SECRET_KEY
        - name: DEBUG
          value: "False"
        ports:
        - containerPort: 8004
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: 8004
          initialDelaySeconds: 30
          periodSeconds: 10

---

# _____________________________ Service for Cart Service _____________________________

apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: ecommerce
  labels:
    app: cart-service
spec:
  selector:
    app: cart-service
  ports:
  - name: http
    protocol: TCP
    port: 8004
    targetPort: 8004
